import Head from "next/head";
import styles from "@App/aboutus/aboutus.module.scss";

export const metadata = {
  title: "Krunal",
  description: "Generated by create next app",
};
export default function AboutUs() {
  return (
    <>
      <main className={`container ${styles.aboutus}`}>
        <h1>About us</h1>
      </main>
    </>
  );
}
