import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Location Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container ${styles.main}`}>
        <h1 className="text-center">Welcome to Next.js!</h1>
        <p className="text-center">
          Get started by editing{" "}
          <code className="bg-dark text-white p-2">pages/index.js</code>
        </p>
        <button className="btn btn-primary">Krunal</button>
      </main>
    </>
  );
}
