import { Providers } from "@/redux/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="">
            <div className="header">Header</div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
